// This file is automatically generated from CMake
#ifndef UTILS_PATHS_H
#define UTILS_PATHS_H

#define RTQL8MANIPULABILITY_ROOT_PATH "H:/dev/rtql8Manipulability/"
#define RTQL8MANIPULABILITY_DATA_PATH "H:/dev/rtql8Manipulability/data/"

#endif // ifndef UTILS_PATHS_H
